spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lab4
    username: lab4
    password: lab4
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    receiver: ${MAIL_RECEIVER}
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  file:
    path: lab4